In [2]:
import pandas as pd

In [3]:
ipl_data = pd.read_csv(r"/home/pavandeep_369/Downloads/IPL.csv")  # change encoding=... if needed

/tmp/ipykernel_21799/4251559413.py:1: DtypeWarning: Columns (0: review_batter, 1: team_reviewed, 2: review_decision, 3: umpire, 4: season, 5: superover_winner, 6: result_type, 7: method, 8: event_match_no) have mixed types. Specify dtype option on import or set low_memory=False.
  ipl_data = pd.read_csv(r"/home/pavandeep_369/Downloads/IPL.csv")  # change encoding=... if needed

In [4]:
staging_data=ipl_data[ipl_data['innings']==2]

In [5]:
staging_data_sorted = staging_data.sort_values(["ball_no"], ascending=[False])
Matches_data = staging_data_sorted.groupby("match_id", as_index=False).head(1)
Matches_data =Matches_data.sort_values(["match_id"], ascending=[True])

In [6]:
Matches_data.head()

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,striker_out,next_batter
224,335982,2008-04-18,T20,Indian Premier League,2,Royal Challengers Bangalore,Kolkata Knight Riders,15,1,15.1,...,91,10,NaN,NaN,3,6,1,P Kumar|SB Joshi,1,NaN
472,335983,2008-04-19,T20,Indian Premier League,2,Kings XI Punjab,Chennai Super Kings,19,6,19.6,...,120,4,NaN,NaN,3,5,0,IK Pathan|SM Katich,0,NaN
691,335984,2008-04-19,T20,Indian Premier League,2,Delhi Daredevils,Rajasthan Royals,15,1,15.1,...,91,1,NaN,NaN,52,41,0,G Gambhir|S Dhawan,0,NaN
937,335985,2008-04-20,T20,Indian Premier League,2,Royal Challengers Bangalore,Mumbai Indians,19,4,19.4,...,118,5,NaN,NaN,3,5,0,B Akhil|MV Boucher,0,NaN
1177,335986,2008-04-20,T20,Indian Premier League,2,Kolkata Knight Riders,Deccan Chargers,18,6,18.6,...,114,5,NaN,NaN,38,43,0,DJ Hussey|LR Shukla,0,NaN

In [7]:
Matches_data=Matches_data.drop(columns=['match_type', 'event_name', 'innings',
        'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
        'day', 'month', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter',
       'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
       'batting_partners', 'striker_out', 'next_batter'])

In [8]:
Matches_data.head(2)

,match_id,date,batting_team,bowling_team,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,year
224,335982,2008-04-18,Royal Challengers Bangalore,Kolkata Knight Riders,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008
472,335983,2008-04-19,Kings XI Punjab,Chennai Super Kings,MEK Hussey,Chennai Super Kings,33 runs,Chennai Super Kings,bat,"Punjab Cricket Association Stadium, Mohali",Chandigarh,2008

In [9]:
Matches_data = Matches_data.rename(columns={"batting_team": "team1", "bowling_team": "team2"})
Matches_data.head()

,match_id,date,team1,team2,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,year
224,335982,2008-04-18,Royal Challengers Bangalore,Kolkata Knight Riders,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008
472,335983,2008-04-19,Kings XI Punjab,Chennai Super Kings,MEK Hussey,Chennai Super Kings,33 runs,Chennai Super Kings,bat,"Punjab Cricket Association Stadium, Mohali",Chandigarh,2008
691,335984,2008-04-19,Delhi Daredevils,Rajasthan Royals,MF Maharoof,Delhi Daredevils,9 wickets,Rajasthan Royals,bat,Feroz Shah Kotla,Delhi,2008
937,335985,2008-04-20,Royal Challengers Bangalore,Mumbai Indians,MV Boucher,Royal Challengers Bangalore,5 wickets,Mumbai Indians,bat,Wankhede Stadium,Mumbai,2008
1177,335986,2008-04-20,Kolkata Knight Riders,Deccan Chargers,DJ Hussey,Kolkata Knight Riders,5 wickets,Deccan Chargers,bat,Eden Gardens,Kolkata,2008

In [12]:
Matches_data[Matches_data['match_won_by']=="Unknown"]

,match_id,date,team1,team2,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,year
15416,392190,2009-04-23,Kolkata Knight Riders,Rajasthan Royals,YK Pathan,Unknown,NaN,Kolkata Knight Riders,field,Newlands,Cape Town,2009
30956,419121,2010-03-21,Chennai Super Kings,Kings XI Punjab,J Theron,Unknown,NaN,Chennai Super Kings,field,"MA Chidambaram Stadium, Chepauk",Chennai,2010
78041,598004,2013-04-07,Sunrisers Hyderabad,Royal Challengers Bangalore,GH Vihari,Unknown,NaN,Royal Challengers Bangalore,bat,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,2013
81445,598017,2013-04-16,Royal Challengers Bangalore,Delhi Daredevils,V Kohli,Unknown,NaN,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2013
99049,729315,2014-04-29,Kolkata Knight Riders,Rajasthan Royals,JP Faulkner,Unknown,NaN,Rajasthan Royals,bat,Sheikh Zayed Stadium,Abu Dhabi,2014
113250,829741,2015-04-21,Kings XI Punjab,Rajasthan Royals,SE Marsh,Unknown,NaN,Kings XI Punjab,field,"Sardar Patel Stadium, Motera",Ahmedabad,2015
121306,829813,2015-05-17,Royal Challengers Bangalore,Delhi Daredevils,Unknown,Unknown,NaN,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2015
144689,1082625,2017-04-29,Mumbai Indians,Gujarat Lions,KH Pandya,Unknown,NaN,Gujarat Lions,bat,Saurashtra Cricket Association Stadium,Rajkot,2017
167177,1175365,2019-03-30,Delhi Capitals,Kolkata Knight Riders,PP Shaw,Unknown,NaN,Delhi Capitals,field,Arun Jaitley Stadium,Delhi,2019
176442,1178424,2019-04-30,Rajasthan Royals,Royal Challengers Bangalore,Unknown,Unknown,NaN,Rajasthan Royals,field,M.Chinnaswamy Stadium,Bengaluru,2019
176909,1178426,2019-05-02,Sunrisers Hyderabad,Mumbai Indians,JJ Bumrah,Unknown,NaN,Mumbai Indians,bat,Wankhede Stadium,Mumbai,2019
179551,1216493,2020-09-20,Kings XI Punjab,Delhi Capitals,MP Stoinis,Unknown,NaN,Kings XI Punjab,field,Dubai International Cricket Stadium,Unknown,2020
187690,1216512,2020-10-18,Sunrisers Hyderabad,Kolkata Knight Riders,LH Ferguson,Unknown,NaN,Sunrisers Hyderabad,field,Sheikh Zayed Stadium,Abu Dhabi,2020
187942,1216517,2020-10-18,Kings XI Punjab,Mumbai Indians,KL Rahul,Unknown,NaN,Mumbai Indians,bat,Dubai International Cricket Stadium,Unknown,2020
181522,1216547,2020-09-28,Mumbai Indians,Royal Challengers Bangalore,AB de Villiers,Unknown,NaN,Mumbai Indians,field,Dubai International Cricket Stadium,Unknown,2020
198492,1254077,2021-04-25,Sunrisers Hyderabad,Delhi Capitals,PP Shaw,Unknown,NaN,Delhi Capitals,bat,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2021
268557,1473469,2025-04-16,Rajasthan Royals,Delhi Capitals,MA Starc,Unknown,NaN,Rajasthan Royals,field,"Arun Jaitley Stadium, Delhi",Delhi,2025
271255,1473481,2025-04-26,Kolkata Knight Riders,Punjab Kings,Unknown,Unknown,NaN,Punjab Kings,bat,"Eden Gardens, Kolkata",Kolkata,2025
287124,1529281,2026-04-26,Lucknow Super Giants,Kolkata Knight Riders,RK Singh,Unknown,NaN,Lucknow Super Giants,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,2026

In [41]:
Matches_data.to_excel(r"/home/pavandeep_369/Work/Matches_Data.xlsx")